# Reading Level Classifier

## Imports

In [67]:
import pandas as pd
import os
import sys
module_path = os.path.abspath(os.path.join(os.pardir, os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)
    
import pandas as pd
import nltk
from nltk.probability import FreqDist
from nltk.corpus import stopwords
from nltk.tokenize import regexp_tokenize, word_tokenize, RegexpTokenizer
import matplotlib.pyplot as plt
import string
import re
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /Users/javm/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [68]:
module_path = os.path.abspath(os.path.join(os.pardir, os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)

## Data Cleaning

### New Feats

In [69]:
new_feat_df = pd.read_csv('/Users/javm/Desktop/Flatiron4/allfeatures-ose-final.csv')
new_feat_df

,fileName,AoA_Bird_Lem,AoA_Bristol_Lem,AoA_Cort_Lem,AoA_Kup,AoA_Kup_Lem,DISC_RefExprDefArtPerSen,DISC_RefExprDefArtPerWord,DISC_RefExprPerProPerWord,DISC_RefExprPerPronounsPerSen,...,PROPORTION_INDEF_NP_REFCHAIN,PROPORTION_DEF_NP_REFCHAIN,PROPORTION_PERSONAL_PRONOUNS_REFCHAIN,PROPORTION_POSSESIVE_DETERMINERS_REFCHAIN,PROPORTION_DEMONSTRATIVE_DETERMINERS_REFCHAIN,PROPORTION_DEMONSTRATIVE_PRONOUNS_REFCHAIN,PROPORTION_REFLEXIVE_PRONOUNS_REFCHAIN,PROPORTION_PROPER_NOUNS_REFCHAIN,AVG_LEN_REFCHAIN,readinglevel
0,Amazon-adv.txt,3.36,1.50,2.44,4.67,6.10,1.25,0.07,0.01,0.22,...,0.200000,0.485714,0.200000,0.0,0.0,0.0,0.000000,0.171429,2.500000,adv
1,Amazon-ele.txt,3.65,1.11,2.43,4.56,5.76,0.84,0.06,0.02,0.27,...,0.115385,0.615385,0.230769,0.0,0.0,0.0,0.000000,0.461538,2.600000,ele
2,Amazon-int.txt,3.51,1.30,2.43,4.60,5.93,1.12,0.07,0.01,0.25,...,0.166667,0.466667,0.233333,0.0,0.0,0.0,0.000000,0.233333,2.727273,int
3,Amsterdam-adv.txt,3.77,1.35,2.57,4.43,5.94,1.31,0.05,0.03,0.89,...,0.179487,0.461538,0.358974,0.0,0.0,0.0,0.000000,0.179487,3.545455,adv
4,Amsterdam-ele.txt,3.82,1.17,2.74,4.36,5.51,1.13,0.05,0.04,0.90,...,0.208333,0.375000,0.416667,0.0,0.0,0.0,0.000000,0.166667,3.692308,ele
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,Zero-Hours-ele.txt,3.98,1.48,2.55,4.47,5.98,0.95,0.04,0.03,0.60,...,0.195122,0.268293,0.317073,0.0,0.0,0.0,0.024390,0.048780,3.727273,ele
563,Zero-Hours-int.txt,4.06,1.40,2.52,4.30,5.98,1.46,0.05,0.02,0.61,...,0.170213,0.382979,0.255319,0.0,0.0,0.0,0.021277,0.021277,3.615385,int
564,climate-change--adv.txt,3.81,1.41,2.45,4.33,5.91,1.16,0.05,0.01,0.40,...,0.185185,0.629630,0.333333,0.0,0.0,0.0,0.000000,0.222222,2.700000,adv
565,climate-change--ele.txt,4.16,1.28,2.68,3.99,5.40,0.96,0.05,0.01,0.27,...,0.320000,0.480000,0.320000,0.0,0.0,0.0,0.000000,0.200000,2.777778,ele
566,climate-change--int.txt,4.05,1.33,2.55,4.02,5.72,1.00,0.05,0.02,0.39,...,0.233333,0.433333,0.366667,0.0,0.0,0.0,0.000000,0.166667,2.727273,int

In [70]:
new_feat_df.rename(columns = {'readinglevel':'Level'}, inplace = True)

In [71]:
new_feat_df.rename(columns = {'fileName':'Title'}, inplace = True)

In [72]:
new_feat_df['Level'].replace(['adv', 'int', 'ele'],
                        [2,1,0], inplace=True)

In [73]:
new_feat_df

,Title,AoA_Bird_Lem,AoA_Bristol_Lem,AoA_Cort_Lem,AoA_Kup,AoA_Kup_Lem,DISC_RefExprDefArtPerSen,DISC_RefExprDefArtPerWord,DISC_RefExprPerProPerWord,DISC_RefExprPerPronounsPerSen,...,PROPORTION_INDEF_NP_REFCHAIN,PROPORTION_DEF_NP_REFCHAIN,PROPORTION_PERSONAL_PRONOUNS_REFCHAIN,PROPORTION_POSSESIVE_DETERMINERS_REFCHAIN,PROPORTION_DEMONSTRATIVE_DETERMINERS_REFCHAIN,PROPORTION_DEMONSTRATIVE_PRONOUNS_REFCHAIN,PROPORTION_REFLEXIVE_PRONOUNS_REFCHAIN,PROPORTION_PROPER_NOUNS_REFCHAIN,AVG_LEN_REFCHAIN,Level
0,Amazon-adv.txt,3.36,1.50,2.44,4.67,6.10,1.25,0.07,0.01,0.22,...,0.200000,0.485714,0.200000,0.0,0.0,0.0,0.000000,0.171429,2.500000,2
1,Amazon-ele.txt,3.65,1.11,2.43,4.56,5.76,0.84,0.06,0.02,0.27,...,0.115385,0.615385,0.230769,0.0,0.0,0.0,0.000000,0.461538,2.600000,0
2,Amazon-int.txt,3.51,1.30,2.43,4.60,5.93,1.12,0.07,0.01,0.25,...,0.166667,0.466667,0.233333,0.0,0.0,0.0,0.000000,0.233333,2.727273,1
3,Amsterdam-adv.txt,3.77,1.35,2.57,4.43,5.94,1.31,0.05,0.03,0.89,...,0.179487,0.461538,0.358974,0.0,0.0,0.0,0.000000,0.179487,3.545455,2
4,Amsterdam-ele.txt,3.82,1.17,2.74,4.36,5.51,1.13,0.05,0.04,0.90,...,0.208333,0.375000,0.416667,0.0,0.0,0.0,0.000000,0.166667,3.692308,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,Zero-Hours-ele.txt,3.98,1.48,2.55,4.47,5.98,0.95,0.04,0.03,0.60,...,0.195122,0.268293,0.317073,0.0,0.0,0.0,0.024390,0.048780,3.727273,0
563,Zero-Hours-int.txt,4.06,1.40,2.52,4.30,5.98,1.46,0.05,0.02,0.61,...,0.170213,0.382979,0.255319,0.0,0.0,0.0,0.021277,0.021277,3.615385,1
564,climate-change--adv.txt,3.81,1.41,2.45,4.33,5.91,1.16,0.05,0.01,0.40,...,0.185185,0.629630,0.333333,0.0,0.0,0.0,0.000000,0.222222,2.700000,2
565,climate-change--ele.txt,4.16,1.28,2.68,3.99,5.40,0.96,0.05,0.01,0.27,...,0.320000,0.480000,0.320000,0.0,0.0,0.0,0.000000,0.200000,2.777778,0
566,climate-change--int.txt,4.05,1.33,2.55,4.02,5.72,1.00,0.05,0.02,0.39,...,0.233333,0.433333,0.366667,0.0,0.0,0.0,0.000000,0.166667,2.727273,1

### Advanced List

In [74]:
adv_list = []
advanced = '/Users/javm/Desktop/Flatiron4/Reading-Level-Classifier/Texts-SeparatedByReadingLevel/Adv-Txt'
for i in (os.listdir(advanced)):
    with open(advanced+'/'+i) as f:
        lines = f.read()
        adv_list.append(lines)

In [75]:
adv_list_title = list(os.listdir(advanced))

In [76]:
# initialize list of lists
data1 = adv_list
# Create the pandas DataFrame
adv_df = pd.DataFrame(data1, columns = ['Text'] )
# print dataframe.
adv_df['Level'] = 2

In [77]:
data11 = adv_list_title
# Create the pandas DataFrame
adv_title_df = pd.DataFrame(data11, columns = ['Title'] )
# print dataframe.
adv_title_df

                                              Title
0                              WNL Shocking-adv.txt
1                           Swedish prisons-adv.txt
2                            WNL John Lewis-adv.txt
3    Facebook deserted by millions of users-adv.txt
4                           WNL Ships noise-adv.txt
..                                              ...
184                     WNL Neuroscientists-adv.txt
185                         WNL Brown bears-adv.txt
186                      WNL Why we should -adv.txt
187                            Prince Harry-adv.txt
188                                   Nepal-adv.txt

[189 rows x 1 columns]

In [78]:
adv_df1 = pd.concat([adv_title_df,adv_df], axis = 1)
adv_df1

,Title,Text,Level
0,WNL Shocking-adv.txt,﻿It was not so much how hard people found the ...,2
1,Swedish prisons-adv.txt,﻿Swedish prisons have long had a reputation ar...,2
2,WNL John Lewis-adv.txt,A lonely old man living in a crater on the moo...,2
3,Facebook deserted by millions of users-adv.txt,﻿Facebook has lost millions of users per month...,2
4,WNL Ships noise-adv.txt,﻿Noise emanating from passing ships may distur...,2
...,...,...,...
184,WNL Neuroscientists-adv.txt,﻿Scientists have created an “atlas of the brai...,2
185,WNL Brown bears-adv.txt,﻿The forests – and suburbs – of Europe are ech...,2
186,WNL Why we should -adv.txt,"﻿James Hamblin, senior editor of American maga...",2
187,Prince Harry-adv.txt,﻿Prince Harry has flown out of Afghanistan at ...,2
188,Nepal-adv.txt,﻿Tigers are more numerous in Nepal than at any...,2

### Intermediate List

In [79]:
int_list = []
intermediate = '/Users/javm/Desktop/Flatiron4/Reading-Level-Classifier/Texts-SeparatedByReadingLevel/Int-Txt'
for i in (os.listdir(intermediate)):
    with open(intermediate+'/'+i) as f:
        lines = f.read()
        int_list.append(lines)
        
#print(int_list)

In [80]:
int_list_title = list(os.listdir(intermediate))

In [81]:
# initialize list of lists
data3 = int_list
# Create the pandas DataFrame
int_df = pd.DataFrame(data3, columns = ['Text'] )
# print dataframe.
int_df['Level'] = 1
int_df

                                                  Text  Level
0    Intermediate \nValdevaqueros is one of the las...      1
1    Intermediate \nThe Duchess of Cambridge gave b...      1
2    Intermediate \nCathal Redmond was swimming off...      1
3    Intermediate \nIt has mapped the worlds highes...      1
4    Intermediate \nThe customer next to you in the...      1
..                                                 ...    ...
184  Intermediate \nEver since he was diagnosed HIV...      1
185  Intermediate \nGalina Zaglumyonova was woken i...      1
186  Intermediate \nAll six numbers match, so its t...      1
187  Intermediate \nAccording to a recent report, t...      1
188  Intermediate \nWhen Larry Pizzi first heard ab...      1

[189 rows x 2 columns]

In [82]:
data22 = int_list_title
# Create the pandas DataFrame
int_title_df = pd.DataFrame(data22, columns = ['Title'] )
# print dataframe.
int_title_df

                           Title
0                  Spain-int.txt
1             Royal Baby-int.txt
2    WNL The lightweight-int.txt
3         Arctic mapping-int.txt
4    WNL Mystery Shopper-int.txt
..                           ...
184              Liberia-int.txt
185            Meteorite-int.txt
186              Loterry-int.txt
187     WNL India's rich-int.txt
188       WNL Can the US-int.txt

[189 rows x 1 columns]

In [83]:
int_df1 = pd.concat([int_title_df,int_df], axis = 1)
int_df1

,Title,Text,Level
0,Spain-int.txt,Intermediate \nValdevaqueros is one of the las...,1
1,Royal Baby-int.txt,Intermediate \nThe Duchess of Cambridge gave b...,1
2,WNL The lightweight-int.txt,Intermediate \nCathal Redmond was swimming off...,1
3,Arctic mapping-int.txt,Intermediate \nIt has mapped the worlds highes...,1
4,WNL Mystery Shopper-int.txt,Intermediate \nThe customer next to you in the...,1
...,...,...,...
184,Liberia-int.txt,Intermediate \nEver since he was diagnosed HIV...,1
185,Meteorite-int.txt,Intermediate \nGalina Zaglumyonova was woken i...,1
186,Loterry-int.txt,"Intermediate \nAll six numbers match, so its t...",1
187,WNL India's rich-int.txt,"Intermediate \nAccording to a recent report, t...",1
188,WNL Can the US-int.txt,Intermediate \nWhen Larry Pizzi first heard ab...,1

In [84]:
int_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    189 non-null    object
 1   Level   189 non-null    int64
dtypes: int64(1), object(1)
memory usage: 3.1+ KB

### Elementary List

In [85]:
ele_list = []
ele = '/Users/javm/Desktop/Flatiron4/Reading-Level-Classifier/Texts-SeparatedByReadingLevel/Ele-Txt'
for i in (os.listdir(ele)):
    with open(ele+'/'+i) as f:
        lines = f.read()
        ele_list.append(lines)
        
#print(ele_list)

In [86]:
ele_list_title = list(os.listdir(ele))

In [87]:
# initialize list of lists
data2 = ele_list
# Create the pandas DataFrame
ele_df = pd.DataFrame(data2, columns = ['Text'] )
# print dataframe.
ele_df['Level'] = 0
ele_df

                                                  Text  Level
0    ﻿SeaWorld’s profits fell by 84% and customers ...      0
1    ﻿Imagine that you read a headline 'Fit in four...      0
2    ﻿Robert Mysłajek stops. Between two paw prints...      0
3    ﻿The Taliban sent a gunman to shoot Malala You...      0
4    ﻿Governments in Europe dream of finding a magi...      0
..                                                 ...    ...
184  ﻿Two scientists at Stanford University, in the...      0
185  ﻿Barack Obama has told young people to reject ...      0
186  ﻿When two people on a remote Pacific island sa...      0
187  ﻿Google has made maps of the world’s highest m...      0
188  ﻿Our new international survey, including 33 co...      0

[189 rows x 2 columns]

In [88]:
data33 = ele_list_title
# Create the pandas DataFrame
ele_title_df = pd.DataFrame(data33, columns = ['Title'] )
# print dataframe.
ele_title_df

                                   Title
0                   WNL SeaWorld-ele.txt
1                       Exercise-ele.txt
2               WNL On the trail-ele.txt
3                         Malala-ele.txt
4                  WNL Novel way-ele.txt
..                                   ...
184         WNL Basic phone logs-ele.txt
185             WNL Barack Obama-ele.txt
186                 WNL Castaway-ele.txt
187           WNL Arctic Ramadan-ele.txt
188  WNL Why are people so wrong-ele.txt

[189 rows x 1 columns]

In [89]:
ele_df1 = pd.concat([ele_title_df,ele_df], axis = 1)
ele_df1

,Title,Text,Level
0,WNL SeaWorld-ele.txt,﻿SeaWorld’s profits fell by 84% and customers ...,0
1,Exercise-ele.txt,﻿Imagine that you read a headline 'Fit in four...,0
2,WNL On the trail-ele.txt,﻿Robert Mysłajek stops. Between two paw prints...,0
3,Malala-ele.txt,﻿The Taliban sent a gunman to shoot Malala You...,0
4,WNL Novel way-ele.txt,﻿Governments in Europe dream of finding a magi...,0
...,...,...,...
184,WNL Basic phone logs-ele.txt,"﻿Two scientists at Stanford University, in the...",0
185,WNL Barack Obama-ele.txt,﻿Barack Obama has told young people to reject ...,0
186,WNL Castaway-ele.txt,﻿When two people on a remote Pacific island sa...,0
187,WNL Arctic Ramadan-ele.txt,﻿Google has made maps of the world’s highest m...,0
188,WNL Why are people so wrong-ele.txt,"﻿Our new international survey, including 33 co...",0

In [90]:
ele_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    189 non-null    object
 1   Level   189 non-null    int64
dtypes: int64(1), object(1)
memory usage: 3.1+ KB

### Combining Data Frames

In [91]:
df1 = adv_df1.merge(int_df1, how = 'outer')
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 378 entries, 0 to 377
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   378 non-null    object
 1   Text    378 non-null    object
 2   Level   378 non-null    int64
dtypes: int64(1), object(2)
memory usage: 11.8+ KB

In [92]:
df2 = df1.merge(ele_df1, how = 'outer')
df2['Title'].replace('-', ' ', regex=True, inplace = True)

In [93]:
new_feat_df['Title'].replace('-', ' ', regex=True, inplace = True)

In [94]:
df2.sort_values(by = 'Title', ascending = False)

,Title,Text,Level
342,climate change int.txt,Intermediate \nLow-income countries will conti...,1
536,climate change ele.txt,﻿Poorer countries will be most affected by cli...,0
55,climate change adv.txt,﻿Low-income countries will remain on the front...,2
197,Zero Hours int.txt,Intermediate \nMore than one million British w...,1
398,Zero Hours ele.txt,﻿More than one million British workers might b...,0
...,...,...,...
520,Amsterdam ele.txt,"﻿To tourists, Amsterdam still seems very liber...",0
35,Amsterdam adv.txt,"﻿Amsterdam still looks liberal to tourists, wh...",2
320,Amazon int.txt,"Intermediate\nWhen you see the word Amazon, wh...",1
523,Amazon ele.txt,"﻿When you see the word Amazon, what’s the firs...",0
30,Amazon adv.txt,"﻿When you see the word Amazon, what’s the firs...",2

In [95]:
print(df2.shape)
print(new_feat_df.shape)

(567, 3)
(567, 157)

In [96]:
df = df2.merge(new_feat_df, on = 'Title', how = 'outer')

In [97]:
df

,Title,Text,Level_x,AoA_Bird_Lem,AoA_Bristol_Lem,AoA_Cort_Lem,AoA_Kup,AoA_Kup_Lem,DISC_RefExprDefArtPerSen,DISC_RefExprDefArtPerWord,...,PROPORTION_INDEF_NP_REFCHAIN,PROPORTION_DEF_NP_REFCHAIN,PROPORTION_PERSONAL_PRONOUNS_REFCHAIN,PROPORTION_POSSESIVE_DETERMINERS_REFCHAIN,PROPORTION_DEMONSTRATIVE_DETERMINERS_REFCHAIN,PROPORTION_DEMONSTRATIVE_PRONOUNS_REFCHAIN,PROPORTION_REFLEXIVE_PRONOUNS_REFCHAIN,PROPORTION_PROPER_NOUNS_REFCHAIN,AVG_LEN_REFCHAIN,Level_y
0,WNL Shocking adv.txt,﻿It was not so much how hard people found the ...,2.0,3.99,1.12,2.83,4.08,5.29,1.22,0.06,...,0.086207,0.275862,0.396552,0.0,0.000000,0.0,0.068966,0.017241,5.272727,2.0
1,Swedish prisons adv.txt,﻿Swedish prisons have long had a reputation ar...,2.0,3.95,1.52,2.58,4.45,5.72,1.00,0.04,...,0.160000,0.373333,0.466667,0.0,0.013333,0.0,0.000000,0.226667,4.166667,2.0
2,WNL John Lewis adv.txt,A lonely old man living in a crater on the moo...,2.0,3.50,1.17,3.00,4.40,5.50,1.73,0.06,...,0.256757,0.527027,0.175676,0.0,0.000000,0.0,0.013514,0.310811,3.083333,2.0
3,Facebook deserted by millions of users adv.txt,﻿Facebook has lost millions of users per month...,2.0,3.57,1.47,2.72,4.12,5.88,1.11,0.05,...,0.196429,0.642857,0.089286,0.0,0.000000,0.0,0.017857,0.517857,3.294118,2.0
4,WNL Ships noise adv.txt,﻿Noise emanating from passing ships may distur...,2.0,3.98,1.32,2.97,4.17,5.78,1.32,0.06,...,0.200000,0.440000,0.200000,0.0,0.000000,0.0,0.000000,0.120000,3.125000,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,WNL Whats the secret ele.txt,NaN,NaN,3.70,1.60,3.05,4.31,5.19,0.71,0.04,...,0.219178,0.164384,0.328767,0.0,0.000000,0.0,0.013699,0.027397,4.562500,0.0
572,WNL Whats the secret int.txt,NaN,NaN,3.79,1.54,2.97,4.51,5.44,0.72,0.04,...,0.132530,0.180723,0.337349,0.0,0.024096,0.0,0.024096,0.036145,4.368421,1.0
573,WNL What is worlds adv.txt,NaN,NaN,3.41,1.40,2.63,4.35,5.71,1.45,0.06,...,0.241379,0.431034,0.103448,0.0,0.000000,0.0,0.000000,0.086207,3.411765,2.0
574,WNL What is worlds ele.txt,NaN,NaN,3.75,1.32,2.81,3.99,5.18,0.95,0.06,...,0.230769,0.596154,0.153846,0.0,0.038462,0.0,0.000000,0.230769,3.058824,0.0
575,WNL What is worlds int.txt,NaN,NaN,3.55,1.37,2.68,4.22,5.48,1.39,0.06,...,0.186047,0.511628,0.162791,0.0,0.000000,0.0,0.000000,0.116279,3.307692,1.0

In [98]:
df.dropna(inplace =True)

In [99]:
df

,Title,Text,Level_x,AoA_Bird_Lem,AoA_Bristol_Lem,AoA_Cort_Lem,AoA_Kup,AoA_Kup_Lem,DISC_RefExprDefArtPerSen,DISC_RefExprDefArtPerWord,...,PROPORTION_INDEF_NP_REFCHAIN,PROPORTION_DEF_NP_REFCHAIN,PROPORTION_PERSONAL_PRONOUNS_REFCHAIN,PROPORTION_POSSESIVE_DETERMINERS_REFCHAIN,PROPORTION_DEMONSTRATIVE_DETERMINERS_REFCHAIN,PROPORTION_DEMONSTRATIVE_PRONOUNS_REFCHAIN,PROPORTION_REFLEXIVE_PRONOUNS_REFCHAIN,PROPORTION_PROPER_NOUNS_REFCHAIN,AVG_LEN_REFCHAIN,Level_y
0,WNL Shocking adv.txt,﻿It was not so much how hard people found the ...,2.0,3.99,1.12,2.83,4.08,5.29,1.22,0.06,...,0.086207,0.275862,0.396552,0.0,0.000000,0.0,0.068966,0.017241,5.272727,2.0
1,Swedish prisons adv.txt,﻿Swedish prisons have long had a reputation ar...,2.0,3.95,1.52,2.58,4.45,5.72,1.00,0.04,...,0.160000,0.373333,0.466667,0.0,0.013333,0.0,0.000000,0.226667,4.166667,2.0
2,WNL John Lewis adv.txt,A lonely old man living in a crater on the moo...,2.0,3.50,1.17,3.00,4.40,5.50,1.73,0.06,...,0.256757,0.527027,0.175676,0.0,0.000000,0.0,0.013514,0.310811,3.083333,2.0
3,Facebook deserted by millions of users adv.txt,﻿Facebook has lost millions of users per month...,2.0,3.57,1.47,2.72,4.12,5.88,1.11,0.05,...,0.196429,0.642857,0.089286,0.0,0.000000,0.0,0.017857,0.517857,3.294118,2.0
4,WNL Ships noise adv.txt,﻿Noise emanating from passing ships may distur...,2.0,3.98,1.32,2.97,4.17,5.78,1.32,0.06,...,0.200000,0.440000,0.200000,0.0,0.000000,0.0,0.000000,0.120000,3.125000,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,WNL Basic phone logs ele.txt,"﻿Two scientists at Stanford University, in the...",0.0,4.16,1.35,2.67,3.88,5.17,1.29,0.07,...,0.172414,0.413793,0.362069,0.0,0.000000,0.0,0.000000,0.051724,4.833333,0.0
563,WNL Barack Obama ele.txt,﻿Barack Obama has told young people to reject ...,0.0,4.20,1.11,2.78,4.29,5.19,1.05,0.05,...,0.181818,0.363636,0.409091,0.0,0.000000,0.0,0.000000,0.227273,4.000000,0.0
564,WNL Castaway ele.txt,﻿When two people on a remote Pacific island sa...,0.0,4.00,1.15,2.88,3.85,4.83,0.93,0.05,...,0.145161,0.354839,0.451613,0.0,0.000000,0.0,0.000000,0.112903,4.769231,0.0
565,WNL Arctic Ramadan ele.txt,﻿Google has made maps of the world’s highest m...,0.0,4.08,0.94,2.96,4.14,4.99,1.16,0.07,...,0.064103,0.500000,0.320513,0.0,0.000000,0.0,0.000000,0.205128,4.105263,0.0
566,WNL Why are people so wrong ele.txt,"﻿Our new international survey, including 33 co...",0.0,4.22,1.12,2.71,4.21,5.41,1.14,0.05,...,0.135593,0.338983,0.254237,0.0,0.000000,0.0,0.000000,0.033898,3.105263,0.0

## Preprocessing

In [100]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from nltk import WordNetLemmatizer # lemmatizer using WordNet
from nltk.corpus import wordnet # imports WordNet
from nltk import pos_tag # nltk's native part of speech tagging

nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/javm/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /Users/javm/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [101]:
class TextPreprocessor(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        
        #define attributes to store if text preprocessing requires fitting from data
        pass
    
    def fit(self, data, y = 0):
        # this is where you would fit things like corpus specific stopwords
        # fit probable bigrams with bigram model in here
        
        # save as parameters of Text preprocessor
        
        return self
    
    def transform(self, data, y = 0):
        fully_normalized_corpus = data.apply(self.process_doc)
        
        return fully_normalized_corpus
        
    
    def process_doc(self, doc):

        #initialize lemmatizer
        wnl = WordNetLemmatizer()
        stop_words = stopwords.words('english')
        
        # helper function to change nltk's part of speech tagging to a wordnet format.
        def pos_tagger(nltk_tag):
            if nltk_tag.startswith('J'):
                return wordnet.ADJ
            elif nltk_tag.startswith('V'):
                return wordnet.VERB
            elif nltk_tag.startswith('N'):
                return wordnet.NOUN
            elif nltk_tag.startswith('R'):
                return wordnet.ADV
            else:         
                return None


        # remove stop words and punctuations, then lower case
        doc_norm = [tok.lower() for tok in word_tokenize(doc) if ((tok.isalpha()) & (tok not in stop_words)) ]

        #  POS detection on the result will be important in telling Wordnet's lemmatizer how to lemmatize

        # creates list of tuples with tokens and POS tags in wordnet format
        wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tag(doc_norm))) 
        doc_norm = [wnl.lemmatize(token, pos) for token, pos in wordnet_tagged if pos is not None]

        return " ".join(doc_norm)

In [102]:
proc = TextPreprocessor()

transformed_train = proc.fit_transform(df['Text'])

In [103]:
prc_steps2 = [('tfid', TfidfVectorizer(min_df = 0.05, max_df = 0.95))]
preprocess_pipeline2 = Pipeline(prc_steps2)

In [127]:
X_tr_proc2 = preprocess_pipeline2.fit_transform(transformed_train)

In [142]:
feat_names = preprocess_pipeline2[
    'tfid'].get_feature_names()

word_vec = pd.DataFrame(X_tr_proc2.toarray(), columns = feat_names)
final_df1 = pd.concat([df, word_vec],1).dropna()

In [143]:
final_df1 = final_df1.drop(columns = ['Text','Title'])
final_df1.rename(columns = {'Level_y':'Level'}, inplace = True)

## Modeling

In [154]:
X = final_df1.drop(columns = ["Level", 'Level_x'])
y = final_df["Level"]

In [155]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [156]:
import sklearn
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.svm import SVC

In [157]:
# defining parameter range 
param_grid = {'C': [0.1, 1, 10, 100],  
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'gamma':['scale', 'auto'],
              'kernel': ['linear']}  
   
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 
 
# print best parameter after tuning 
print(grid.best_params_) 
grid_predictions2 = grid.predict(X_test) 
   
# print classification report 
print(classification_report(y_test, grid_predictions2))

Fitting 5 folds for each of 8 candidates, totalling 40 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:   10.3s
[Parallel(n_jobs=-1)]: Done  40 out of  40 | elapsed:   50.2s finished

{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}
              precision    recall  f1-score   support

         0.0       0.76      0.90      0.83        50
         1.0       0.68      0.52      0.59        65
         2.0       0.70      0.78      0.74        50

    accuracy                           0.72       165
   macro avg       0.71      0.73      0.72       165
weighted avg       0.71      0.72      0.71       165

In [161]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.896969696969697

In [163]:
param_grid_rf = {'max_depth': [3, 5, 10],
              'min_samples_split': [2, 5, 10]}  
   
grid = GridSearchCV(rf, param_grid_rf, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 
 
# print best parameter after tuning 
print(grid.best_params_) 
grid_predictions2 = grid.predict(X_test) 
   
# print classification report 
print(classification_report(y_test, grid_predictions2))

Fitting 5 folds for each of 9 candidates, totalling 45 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    1.8s
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:    2.6s finished

{'max_depth': 10, 'min_samples_split': 2}
              precision    recall  f1-score   support

         0.0       0.87      0.94      0.90        50
         1.0       0.86      0.88      0.87        65
         2.0       0.91      0.82      0.86        50

    accuracy                           0.88       165
   macro avg       0.88      0.88      0.88       165
weighted avg       0.88      0.88      0.88       165